{{- range until (.Values.virtualServiceCount | int) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ $.Chart.Name }}-{{.}}"
spec:
  hosts:
  - vs{{.}}.{{ $.Values.istioDomain }}
  gateways:
  - "{{ $.Chart.Name }}-gateway"
  http:
  - route:
    - destination:
        host: {{ $.Chart.Name }}
        port:
          number: 80
---
{{- end }} 