istioDomain: localhost
virtualServiceCount: 30
nginx:
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "100Mi"
      cpu: "128m"
    limits:
      memory: "200Mi"
      cpu: "256m"

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpu: 80
  memory: 200Mi